[blue_marble_regular_april]
git-tree-sha1 = "bd5221cd783880e79f23019a1e1300c48edf4404"
lazy = true

    [[blue_marble_regular_april.download]]
    sha256 = "a2d301cc1302210c3642229177b839ec6a328e62982ba6c71f916999b6454e8a"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_april.tar.gz"

[blue_marble_regular_august]
git-tree-sha1 = "d36169bbe0723d191f262ec5a80e3bd9a1ec03e1"
lazy = true

    [[blue_marble_regular_august.download]]
    sha256 = "04ed13fcca576b31033bb8ef6bf4175d7afdf19d5a4014705e85afecd86da4ba"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_august.tar.gz"

[blue_marble_regular_december]
git-tree-sha1 = "d843139f4cd8516419fe0c44c4755f5c097ddf57"
lazy = true

    [[blue_marble_regular_december.download]]
    sha256 = "2950830752efd486215615cbc2b1cd4b56cd02e8563e819a5f17467de7b4d54b"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_december.tar.gz"

[blue_marble_regular_february]
git-tree-sha1 = "2e56451fb12fa77ad9fd07b224f0590ca2b74369"
lazy = true

    [[blue_marble_regular_february.download]]
    sha256 = "1be4fd2d729d8c5350da81ce52e822ff761ce0ae7caa90bd3dbe551bec0b805d"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_february.tar.gz"

[blue_marble_regular_january]
git-tree-sha1 = "49c43ecbf2c2b7c177337f8134841bae9fa44392"
lazy = true

    [[blue_marble_regular_january.download]]
    sha256 = "745382287fe7322f019a8def40ec8d87ee8a9c64f0c8c747b32426709b781ded"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_january.tar.gz"

[blue_marble_regular_july]
git-tree-sha1 = "e75da08894e4f61088a4a7e8705cb6ffbdb659bc"
lazy = true

    [[blue_marble_regular_july.download]]
    sha256 = "94b63d65004b9e68127200748a41e6dc05f77598276727ab7312f37d44a3ddfd"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_july.tar.gz"

[blue_marble_regular_june]
git-tree-sha1 = "f20ec14199ba221e74c377e2c6fab8dfd00943a5"
lazy = true

    [[blue_marble_regular_june.download]]
    sha256 = "4de07479755f5dd88ce908f3a23017a6e0aaf33b4b49ee483201592f18713f00"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_june.tar.gz"

[blue_marble_regular_march]
git-tree-sha1 = "a2375bc356d06fcf9cf8fb886345a9c5c8b70965"
lazy = true

    [[blue_marble_regular_march.download]]
    sha256 = "ce1d42d74f5209444fcd197794bc6101b243b2d99c4da9b449afa598fb99d252"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_march.tar.gz"

[blue_marble_regular_may]
git-tree-sha1 = "c6326d393ef6f4fb4f92a1a8d3faa94196b5fcc3"
lazy = true

    [[blue_marble_regular_may.download]]
    sha256 = "446e19d8e9453eae11009ac23c0299dae0acadbdd5fcad8fb072086020e3448e"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_may.tar.gz"

[blue_marble_regular_november]
git-tree-sha1 = "8560877823fc4f368c5ec0c3ffdfa741c0b12f2f"
lazy = true

    [[blue_marble_regular_november.download]]
    sha256 = "7e5744f93d466b37b88a00389b0b18a4502766306133d4a1c32fb94988b5f3e8"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_november.tar.gz"

[blue_marble_regular_october]
git-tree-sha1 = "4efb7af65d30843c2ac6820fc1f5bfe34013ac88"
lazy = true

    [[blue_marble_regular_october.download]]
    sha256 = "228ab3c18a0facc8b6131359f8deb9be6fb3adc1e99b58f2cc955f1d41048fb7"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_october.tar.gz"

[blue_marble_regular_september]
git-tree-sha1 = "bfbbf15f49f0d06d060524a3e1bf18ca4407a888"
lazy = true

    [[blue_marble_regular_september.download]]
    sha256 = "9da83e184ee4fc6d13d32a46e5551ac541cd6d3fbde4b6ff555d872248155830"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_september.tar.gz"

[blue_marble_topo_april]
git-tree-sha1 = "9a177f694b708267380a3f96b51c685ff074f259"
lazy = true

    [[blue_marble_topo_april.download]]
    sha256 = "fe280b79666126b50c40ada56275fed8cb253127af705946f1f9bd1abd2e4487"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_april.tar.gz"

[blue_marble_topo_august]
git-tree-sha1 = "65f3771b502bb3d275314e0f8fe903512cb59e42"
lazy = true

    [[blue_marble_topo_august.download]]
    sha256 = "803504cdb0672f1a784ee71e1d903be3dde4bf652b0f12da0b9778255d5c0554"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_august.tar.gz"

[blue_marble_topo_bathy_april]
git-tree-sha1 = "9ff0d5b9a1c499b8f24ac9fa1fa1de86d3c1b9a7"
lazy = true

    [[blue_marble_topo_bathy_april.download]]
    sha256 = "eb265cb3d93627f88841ae2ef0bf6b2b8f7881473097261859dd4e7d1f8fa8ef"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_april.tar.gz"

[blue_marble_topo_bathy_august]
git-tree-sha1 = "4b90f89ce0b94496109a0484bd1598778efa8d91"
lazy = true

    [[blue_marble_topo_bathy_august.download]]
    sha256 = "cefb89e61a29d44cdd339aee54ab6ca8ca79da611d6cb0ba29ecccfbd8bdc19b"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_august.tar.gz"

[blue_marble_topo_bathy_december]
git-tree-sha1 = "1ecf0d51950dcb4e6879c8fb386041b1ec459102"
lazy = true

    [[blue_marble_topo_bathy_december.download]]
    sha256 = "3b6df10724612f850aa9ec9774efa797de4c52dbc951ccdc71667b8a1677d9eb"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_december.tar.gz"

[blue_marble_topo_bathy_february]
git-tree-sha1 = "b55418a2d88f0288a9c3bf7e22da3e5c2bcbc8b9"
lazy = true

    [[blue_marble_topo_bathy_february.download]]
    sha256 = "45d3ee3700805bed0e6ea45b21df7c262c773516e664d3c3999c8fd3e832b933"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_february.tar.gz"

[blue_marble_topo_bathy_january]
git-tree-sha1 = "cadd47f53b30246150ad1da6a929f40be8a43c47"
lazy = true

    [[blue_marble_topo_bathy_january.download]]
    sha256 = "cdd988c27fb3ee63150737a0cf5e75f2647e9aa3b0dc528673747afc9f82a30d"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_january.tar.gz"

[blue_marble_topo_bathy_july]
git-tree-sha1 = "9ca4c8fb404494c18c8ac2c93499ca8e9ea01f9b"
lazy = true

    [[blue_marble_topo_bathy_july.download]]
    sha256 = "bdadc960ddf9506b53069a82ee14f56fb7121e2e1c82a28499b404f1c7fe27a0"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_july.tar.gz"

[blue_marble_topo_bathy_june]
git-tree-sha1 = "7a177171db7374de56f11f08f2d29d2b54457eb5"
lazy = true

    [[blue_marble_topo_bathy_june.download]]
    sha256 = "fe06c6a627dec6aa607c2eb9ee8aefefc0dff241ec15c748c24c629f4d1e9b63"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_june.tar.gz"

[blue_marble_topo_bathy_march]
git-tree-sha1 = "af35631fa2354ce3c7094c185954c4c2a89302be"
lazy = true

    [[blue_marble_topo_bathy_march.download]]
    sha256 = "8b2a0cb5a34bfd294ec5f30ff5b58a308fdf448bcf73839bb2ecd083eecdaa87"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_march.tar.gz"

[blue_marble_topo_bathy_may]
git-tree-sha1 = "c976d00c5debce96716bf56168bcb929a85b1f36"
lazy = true

    [[blue_marble_topo_bathy_may.download]]
    sha256 = "ab218e3e576fa01d943aca049b0dbf76120cc91d552e8a3ed2037cf4072bf438"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_may.tar.gz"

[blue_marble_topo_bathy_november]
git-tree-sha1 = "1ba5e344ee7f3b467a87563589aaa798102b0a91"
lazy = true

    [[blue_marble_topo_bathy_november.download]]
    sha256 = "d620b1715cd3f4f720d26f8bc6c0b4d4eb0288d2ffe089096831d491eefc5db5"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_november.tar.gz"

[blue_marble_topo_bathy_october]
git-tree-sha1 = "efa7898a22ed0b94084af2925f5c88d7eb4e94d7"
lazy = true

    [[blue_marble_topo_bathy_october.download]]
    sha256 = "bf213776d348ed1492cca4f1b8b9fe28906952719ffee56fef73ca33db2b7f44"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_october.tar.gz"

[blue_marble_topo_bathy_september]
git-tree-sha1 = "3ec7c37dc345c4bcf502b7c1ffb5c33c913dc20c"
lazy = true

    [[blue_marble_topo_bathy_september.download]]
    sha256 = "8714ceefc9b11522f28ba054b945c2af7b1b9ce2e4f6742e8425f32634a2d171"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_september.tar.gz"

[blue_marble_topo_december]
git-tree-sha1 = "5c35bfa00ccfdeea87ad0f5127c84c2dd473e87d"
lazy = true

    [[blue_marble_topo_december.download]]
    sha256 = "79ec921c81c40edd47af51b94d5f3690a41ca32cbce2293bb2d1a16acd1aaf7b"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_december.tar.gz"

[blue_marble_topo_february]
git-tree-sha1 = "8d0956a981a3c4a90a5bd236368c33b2d643d2a7"
lazy = true

    [[blue_marble_topo_february.download]]
    sha256 = "ba2c8a754f5355da5494d63ffe30ab912654edda3a2bc4e6807517f0e50b56b3"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_february.tar.gz"

[blue_marble_topo_january]
git-tree-sha1 = "a3dc6e7d95253956fa5819b6f1d189c0fdb5d51d"
lazy = true

    [[blue_marble_topo_january.download]]
    sha256 = "bb7e689cf1da949fb160b734be37d003e6a2805784c1b340c04d5014e7ca89ac"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_january.tar.gz"

[blue_marble_topo_july]
git-tree-sha1 = "d3a9917e26fc3cc9267e5d05f3aa158aa1170cc5"
lazy = true

    [[blue_marble_topo_july.download]]
    sha256 = "c63a526c4bc66fd36942ede93de4698aa80f7fbec61b46dfbe68ee82a7035092"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_july.tar.gz"

[blue_marble_topo_june]
git-tree-sha1 = "36f635a6fb0337f6ba4d821d2f106efeb20e87c0"
lazy = true

    [[blue_marble_topo_june.download]]
    sha256 = "96126047d09bc114ed87d16772a3d76e0fdfecba77d70f66ce5e58c2b6ea3efa"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_june.tar.gz"

[blue_marble_topo_march]
git-tree-sha1 = "ecff6e353733da9fa62f3a25820d5545ad7386d5"
lazy = true

    [[blue_marble_topo_march.download]]
    sha256 = "f3f30e06612a4f546c832162b3867c983c6ce2917530c3879461433283509b90"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_march.tar.gz"

[blue_marble_topo_may]
git-tree-sha1 = "8344ca4042c384697fba81969e18ec1262629cc2"
lazy = true

    [[blue_marble_topo_may.download]]
    sha256 = "798f91d470535b3377fdc45dcfa0bf9ca8ff5c8bd614c7c880f4e23e434a6dc7"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_may.tar.gz"

[blue_marble_topo_november]
git-tree-sha1 = "c29954192c0e852f05ef36f33d79d135e2622b79"
lazy = true

    [[blue_marble_topo_november.download]]
    sha256 = "038fc8d9c12404050ada0b75f126f9db2388f130e2da8ffc6cf04b197f569f56"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_november.tar.gz"

[blue_marble_topo_october]
git-tree-sha1 = "dfbc9a62fc0258d2a2c0279d1a8a07e4b89c6347"
lazy = true

    [[blue_marble_topo_october.download]]
    sha256 = "154f362ed16f5632ee6f9c74b616ef6d2c03b9801c01efb404c8db97f1812bd1"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_october.tar.gz"

[blue_marble_topo_september]
git-tree-sha1 = "e61a4dfa83876066139213f4c61a59550db7df10"
lazy = true

    [[blue_marble_topo_september.download]]
    sha256 = "b00e71838c44910d449172d43c4f073a323e1ed0d37b6f7086030a982a88e8b8"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_september.tar.gz"

[ne_10m_admin_0_countries]
git-tree-sha1 = "fe070f47e1108c86e37eba69bc8cbc360be0af3c"

    [[ne_10m_admin_0_countries.download]]
    sha256 = "f4c0fb159b98b2df0c7a4873745e959a972fd250026ad18224e067ac2c6ee7a1"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_10m_admin_0_countries.tar.gz"

[ne_10m_coastline]
git-tree-sha1 = "add3d68ecb8efe2d06e832edfcda2b9fca2142a2"

    [[ne_10m_coastline.download]]
    sha256 = "638bcaeb8b8b5aaa2949d175fd27e6c5be16b0427f49bf59de293471c78dfb40"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_10m_coastline.tar.gz"

[ne_10m_land]
git-tree-sha1 = "f6c3b15c51855a216319b60b85deb58a45d9ebe2"

    [[ne_10m_land.download]]
    sha256 = "457eb32ca5ada2805990c0e979119b28f78b0bfa4f138673ed070a257bd71a1d"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_10m_land.tar.gz"

[ne_10m_populated_places]
git-tree-sha1 = "14ec6f59f97514e59637d6300943821a765b9a08"
lazy = true

    [[ne_10m_populated_places.download]]
    sha256 = "0ceaa2da98ab7f932d3d8e7c6cd9f2e00b243c6948cd491f0e9da18bd8b5c2fb"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_10m_populated_places.tar.gz"

[ne_110m_admin_0_countries]
git-tree-sha1 = "7df8c74343180be5162d869a9d5dfdd491af967f"

    [[ne_110m_admin_0_countries.download]]
    sha256 = "60cfd0d7c3ceeb030d72b8a30e67207776beb5d50dafe2c0bdbc5a80c79c3ea4"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_110m_admin_0_countries.tar.gz"

[ne_110m_coastline]
git-tree-sha1 = "239d88cf1df6b1fa51bf487cf4b36d4f897380af"

    [[ne_110m_coastline.download]]
    sha256 = "5846bb9986aa6fdc34b977e57f1e0d4e86711e2cb7ef6ccd1ffbd96c46353165"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_110m_coastline.tar.gz"

[ne_110m_land]
git-tree-sha1 = "73e8d1afbb7632d48fedfabbf9c780d635262e20"

    [[ne_110m_land.download]]
    sha256 = "35360e7bf57fab062b26eda1c30b249f909370119dc0eca6a3e37d980c4fa047"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_110m_land.tar.gz"

[ne_110m_populated_places]
git-tree-sha1 = "c55a0ec4d25c26f5d61da03eff8abcc015aed4fa"

    [[ne_110m_populated_places.download]]
    sha256 = "47dfa419bbda59825fd1110055b1a0992ef0c2fd3c5a5dad045317c5ec266237"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_110m_populated_places.tar.gz"

[ne_50m_admin_0_countries]
git-tree-sha1 = "cf6c37f38f2a829b92044cc126ce82cce7c75fa1"

    [[ne_50m_admin_0_countries.download]]
    sha256 = "b517b1923796b4ab7182f1607b1486de242f772ddd0344011bba057f7064b728"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_50m_admin_0_countries.tar.gz"

[ne_50m_coastline]
git-tree-sha1 = "ee361154f193deaa4c4f138d778667d6f520d18c"

    [[ne_50m_coastline.download]]
    sha256 = "e1c22d61d60e6744368ef918f55d3f658a4ba172eb84cd3e69a00b1dc3451614"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_50m_coastline.tar.gz"

[ne_50m_land]
git-tree-sha1 = "f4bb2b31ed0e89e79fd9954cfcbfbf7699eaccdc"

    [[ne_50m_land.download]]
    sha256 = "0caaf3cb6151ea5a29a9b1a7403631d693c9efbc4bc749fe8f118f3840cd7aed"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_50m_land.tar.gz"

[ne_50m_populated_places]
git-tree-sha1 = "79dd0a1a902bd8b350192108cf8766f383ec1bd4"

    [[ne_50m_populated_places.download]]
    sha256 = "7f247ddf945066e6f7af7d6dde361e40a02fdc092da999f0d2a96f94671a45a9"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_50m_populated_places.tar.gz"

[skymap]
git-tree-sha1 = "4c00324268b27d1685fa54ddfcb3d9ba32f147c7"
lazy = true

    [[skymap.download]]
    sha256 = "b035cb0606b592f371559e13bf88f0ce907ef77af757b85eae18cc1733a47a4d"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/skymap.tar.gz"
