[blue_marble_regular_april]
git-tree-sha1 = "85defa97d9ab154e66e3ead597b95dff2beae9df"
lazy = true

    [[blue_marble_regular_april.download]]
    sha256 = "44766f1eb1e2197cf6f46c032885c660a130f857c32ba8f1ac9dd67a6dea3fe9"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_april.tar.gz"

[blue_marble_regular_august]
git-tree-sha1 = "8b5eb2b6b0f39f1e06c664bdda72ffbde18cf031"
lazy = true

    [[blue_marble_regular_august.download]]
    sha256 = "4e6a29e3028de4d74069f20d541ef0e2736d426b794c3505197488a8cdd75b0f"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_august.tar.gz"

[blue_marble_regular_december]
git-tree-sha1 = "b65266a79411ef0402a002ba95a27ff4b4cd003a"
lazy = true

    [[blue_marble_regular_december.download]]
    sha256 = "72d8e042661be2c09feb76030ee7278e0dd75a20ad1a16957e98457ab1cc70f9"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_december.tar.gz"

[blue_marble_regular_february]
git-tree-sha1 = "cb62a0c9f39e7061f7c31dff2106341970717cca"
lazy = true

    [[blue_marble_regular_february.download]]
    sha256 = "713bb91f3712d5e1e673d55aae68ce73d3cf506a19d124f76876d5938189586d"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_february.tar.gz"

[blue_marble_regular_january]
git-tree-sha1 = "1782ff14b50c2796b2adc5f0ecdd1c8bbddb47f5"
lazy = true

    [[blue_marble_regular_january.download]]
    sha256 = "33aca9cf811a0b1d8796ff67ee79236939f1f5d0ea855d0fa5558b5efa7ebf6c"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_january.tar.gz"

[blue_marble_regular_july]
git-tree-sha1 = "820df260905421646281722393b4d91133efd0b6"
lazy = true

    [[blue_marble_regular_july.download]]
    sha256 = "417f28d27186783fa171fb33b149fbb535e572609563b7ef6fdcacb9a2009bea"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_july.tar.gz"

[blue_marble_regular_june]
git-tree-sha1 = "b93ab3961ed862746b4e6095da67745735fc1a48"
lazy = true

    [[blue_marble_regular_june.download]]
    sha256 = "86c362f26d78d2895797feb56ad57f22b3200cfd1aa7b0041931b3c256113a60"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_june.tar.gz"

[blue_marble_regular_march]
git-tree-sha1 = "f355fd089eb2e09a3350ede91e395fad1d954020"
lazy = true

    [[blue_marble_regular_march.download]]
    sha256 = "20f3b2e589e1d009e60653b190686b84dc45c57b1ed38b7f2e252c57eed9d1c3"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_march.tar.gz"

[blue_marble_regular_may]
git-tree-sha1 = "6a170fa2b7ac437cee7fbcc63fcef72e325f0648"
lazy = true

    [[blue_marble_regular_may.download]]
    sha256 = "2876c29bdfc35110edc82b780f0725805fd17c4bb0383c350dfbf7b390df8576"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_may.tar.gz"

[blue_marble_regular_november]
git-tree-sha1 = "8faa1119724f813e620411cc9a6fc661704d3e78"
lazy = true

    [[blue_marble_regular_november.download]]
    sha256 = "e95d4c7e46db53b398b9ba568624ba6ff72f97000a26992e95c1446cc8ba13ae"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_november.tar.gz"

[blue_marble_regular_october]
git-tree-sha1 = "7abc6d1d1220187944989fec268450e144331b86"
lazy = true

    [[blue_marble_regular_october.download]]
    sha256 = "66f906e5ee2e74220f5080c6bd36d2022aba0700a1454f93b37e94e09bb56e3a"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_october.tar.gz"

[blue_marble_regular_september]
git-tree-sha1 = "038b01377efa2265073ffb9ff30a4b0b8f012de6"
lazy = true

    [[blue_marble_regular_september.download]]
    sha256 = "be8313be9cae711045c37b93e41114a50f338f9a9d5052d10abb068eb960b3d1"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_regular_september.tar.gz"

[blue_marble_topo_april]
git-tree-sha1 = "edc976da8992f7c84610f08262941ed867d0ed65"
lazy = true

    [[blue_marble_topo_april.download]]
    sha256 = "b614eb3d81e695afbfec805124af5e6646c1e6841b114c283d6efb0b44c0eff0"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_april.tar.gz"

[blue_marble_topo_august]
git-tree-sha1 = "8eb884c61efd172d8103fc7d75b48724c4c5df0c"
lazy = true

    [[blue_marble_topo_august.download]]
    sha256 = "aafb710ed3fcca1893c65ae8928ed2e823bc1775121a3ccb1f2cbaf96d790e6f"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_august.tar.gz"

[blue_marble_topo_bathy_april]
git-tree-sha1 = "bcedffa0be883e72390d45cad1a1243fa6817b2f"
lazy = true

    [[blue_marble_topo_bathy_april.download]]
    sha256 = "6e132d2922e5c4a417e1577b500bca47400b0993ea3b8ab4eadcbc44bfdf4816"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_april.tar.gz"

[blue_marble_topo_bathy_august]
git-tree-sha1 = "6b361886c86f62163dc3359fe7fd7ed36cdcfef7"
lazy = true

    [[blue_marble_topo_bathy_august.download]]
    sha256 = "9105898cac7de0387761284b2d9e6a2a90d4b56278fee9557a8017409813f807"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_august.tar.gz"

[blue_marble_topo_bathy_december]
git-tree-sha1 = "4524bde965c51564de2b4f34ebba465c0551a047"
lazy = true

    [[blue_marble_topo_bathy_december.download]]
    sha256 = "11b08ce3bf6fac6e79c393e8922801ddd93860e4efed87557eb10057ac868a40"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_december.tar.gz"

[blue_marble_topo_bathy_february]
git-tree-sha1 = "f1d8e656d1ff15fc34baf7de9cbb0a660b8f2822"
lazy = true

    [[blue_marble_topo_bathy_february.download]]
    sha256 = "8e2c62137877219eb5c49e29eeddc4a2702700e6d095fc9f3ae70c74e5a5ec8b"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_february.tar.gz"

[blue_marble_topo_bathy_january]
git-tree-sha1 = "7f51abd376644826911d242434acb1c4e4e83bdc"
lazy = true

    [[blue_marble_topo_bathy_january.download]]
    sha256 = "5cde3490cc6b50b6558faecdbd966d1eee23a982f3b6bcccaeccd7e25f2fa45f"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_january.tar.gz"

[blue_marble_topo_bathy_july]
git-tree-sha1 = "4e0c098101b004bbd653372bccfd192ff73b9747"
lazy = true

    [[blue_marble_topo_bathy_july.download]]
    sha256 = "9b5add4b55db857e7afb2b3f7150d045bcdd84fd5a7c89b0fc36d2868ca07b88"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_july.tar.gz"

[blue_marble_topo_bathy_june]
git-tree-sha1 = "2ddcc929ba03b59eff5c19b8ca5f605cbae38e6d"
lazy = true

    [[blue_marble_topo_bathy_june.download]]
    sha256 = "1b0d64381f65d20d1b0b885f6f79fdefb31387e24dc11c461f9d9e993e585016"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_june.tar.gz"

[blue_marble_topo_bathy_march]
git-tree-sha1 = "d0dcc107eaec83972c77984a5f86a6e789437dfb"
lazy = true

    [[blue_marble_topo_bathy_march.download]]
    sha256 = "0ef13c759bb004af45dece6f2ea907a6f35959c94669e6b9063bd1b1eabb82c5"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_march.tar.gz"

[blue_marble_topo_bathy_may]
git-tree-sha1 = "c91b27fdf1f0a8f61af67e05e5510cfca56df1f9"
lazy = true

    [[blue_marble_topo_bathy_may.download]]
    sha256 = "97feb06ca8b18e5c29506280df6372511ae8a6e8faffdf278e1e24a6ef55ca6e"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_may.tar.gz"

[blue_marble_topo_bathy_november]
git-tree-sha1 = "9cc98705e6e58371ae91723e4f2d4e9e82150b2d"
lazy = true

    [[blue_marble_topo_bathy_november.download]]
    sha256 = "794d50d23ab06dc420348e7ba7d62246ac421986913acb87ceda953429547815"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_november.tar.gz"

[blue_marble_topo_bathy_october]
git-tree-sha1 = "5b9db2fe3924ce2acecfaf52bffc41b485c28084"
lazy = true

    [[blue_marble_topo_bathy_october.download]]
    sha256 = "77352ee3cf264a7013e68920412a87858c5e690ecdcf19a20bccab2f89e6404e"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_october.tar.gz"

[blue_marble_topo_bathy_september]
git-tree-sha1 = "3aed136f0332653dec325064237cf1ce91018c40"
lazy = true

    [[blue_marble_topo_bathy_september.download]]
    sha256 = "81a67ee234b883cee73f19974010e1c9812b99ede37287db9c30336fdc8b7e4c"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_bathy_september.tar.gz"

[blue_marble_topo_december]
git-tree-sha1 = "24baa33c8bb752323e1283a6f1d3c5140db054d3"
lazy = true

    [[blue_marble_topo_december.download]]
    sha256 = "e4ddcba24bc9bc65ca6d57abbc7a49794dcfe6d7f4793bc696762aed8a219bab"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_december.tar.gz"

[blue_marble_topo_february]
git-tree-sha1 = "e73f37aa7eaf8e81a42fee792514b1a34b7851aa"
lazy = true

    [[blue_marble_topo_february.download]]
    sha256 = "db79cf238c233a8fc89622599e8a69a3f83bcbf90b6775b10efbbfd1ccd7c99c"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_february.tar.gz"

[blue_marble_topo_january]
git-tree-sha1 = "4d70d08d7212aed17ae5611c523983ebdceac482"
lazy = true

    [[blue_marble_topo_january.download]]
    sha256 = "983eba285993c41e56389d34f921d869ee410dd13cc54b8bf08a51300d6aa5ed"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_january.tar.gz"

[blue_marble_topo_july]
git-tree-sha1 = "673c14fab4ba9777f17c881657eb6801414a8546"
lazy = true

    [[blue_marble_topo_july.download]]
    sha256 = "2fe79c12b1971f87c4d952607f9f0899fd5b4f4d6da63079123274995b644b62"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_july.tar.gz"

[blue_marble_topo_june]
git-tree-sha1 = "0c804aa95f734905e8434dcf7c0c932349ab9650"
lazy = true

    [[blue_marble_topo_june.download]]
    sha256 = "5908864d0d6c0eca1f57e554be84f21fd0743e96dbbfca28a5aba62e49fa9296"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_june.tar.gz"

[blue_marble_topo_march]
git-tree-sha1 = "eb627e36f94096a02d42ac14d6d1cf411515b652"
lazy = true

    [[blue_marble_topo_march.download]]
    sha256 = "81686a14729c1a29f6b5d3cc383c5123b44e2a33a073584ee2e9b2a4c8d63523"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_march.tar.gz"

[blue_marble_topo_may]
git-tree-sha1 = "64081511b3f57f19af62d437f4da691cc47012c1"
lazy = true

    [[blue_marble_topo_may.download]]
    sha256 = "28b3c06c853257de433f0432e4fb90794f488c49f51a3bc44fc27365e81a4e31"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_may.tar.gz"

[blue_marble_topo_november]
git-tree-sha1 = "24c4bb83f390d4319c4d39b416b29a4b05d7a4c9"
lazy = true

    [[blue_marble_topo_november.download]]
    sha256 = "c5a54ae8944a2d12432d479bf7dcd37bbd71853f5e41a8a3f4dfdb86c450d3cb"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_november.tar.gz"

[blue_marble_topo_october]
git-tree-sha1 = "4af63beb641cd37b8daf6376ae2bf80238efb865"
lazy = true

    [[blue_marble_topo_october.download]]
    sha256 = "18889e1fa427a9ded38eeb1be22e9496ae7f9de589c2afb1293883bcf6b09035"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_october.tar.gz"

[blue_marble_topo_september]
git-tree-sha1 = "82441ca52ab3011e1fab57d09c2203d6aea22f29"
lazy = true

    [[blue_marble_topo_september.download]]
    sha256 = "38a5fae57ea133b519fce735e9262ecc9702ebf1b3983a31652457592168a4fe"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/blue_marble_topo_september.tar.gz"

[ne_10m_admin_0_countries]
git-tree-sha1 = "8e53682adc87fb8f348111a7531f5bf42d10e1b5"

    [[ne_10m_admin_0_countries.download]]
    sha256 = "1927b92cc88f8dab6f8ddcae05fb315eaa9d81deb51566f04ee3294139f07d60"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_10m_admin_0_countries.tar.gz"

[ne_10m_coastline]
git-tree-sha1 = "d63e45897c2fe0d6ae75a50b406f2f8cc794067b"

    [[ne_10m_coastline.download]]
    sha256 = "d14a97952f4f940c7abc076b551a2d2f8c51cd14dfb38a628f78802e20a94b6f"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_10m_coastline.tar.gz"

[ne_10m_land]
git-tree-sha1 = "8b7f3f99157c2a171d4b601c6abd19c5ef4aad12"

    [[ne_10m_land.download]]
    sha256 = "b15fcdde49bfa9e198d23e4c5bc51ede80463f6b915af00b513589c10de74827"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_10m_land.tar.gz"

[ne_10m_populated_places]
git-tree-sha1 = "4e1f1bc9bd8d52c74bf83d00847e08b11a48a7bb"
lazy = true

    [[ne_10m_populated_places.download]]
    sha256 = "f97741632e8fa8e3f79625138f7687b08b4548768e591b5da3362a9873839368"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_10m_populated_places.tar.gz"

[ne_110m_admin_0_countries]
git-tree-sha1 = "6ea149eccce8f1986d43b9f58ec51811a88363c0"

    [[ne_110m_admin_0_countries.download]]
    sha256 = "ff5b038b5e1bd05f4cb6a8b0b7c5d66d9c43ca5277f922e36f401d9ac5a2812f"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_110m_admin_0_countries.tar.gz"

[ne_110m_coastline]
git-tree-sha1 = "1537a97c520465041a08ccafb0bde37cc7fc0677"

    [[ne_110m_coastline.download]]
    sha256 = "4062ed04e0da32ee55eb2ed70aee0e5a2da349fa4ff4ea64ad596b589715b901"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_110m_coastline.tar.gz"

[ne_110m_land]
git-tree-sha1 = "898eab259cafb0fcf466a837e6656f9e56e654f8"

    [[ne_110m_land.download]]
    sha256 = "1a5f627d728fdb0f08f150feb16d41e9b969176561ac60d44d4a55b6161ebd3a"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_110m_land.tar.gz"

[ne_110m_populated_places]
git-tree-sha1 = "aa1575188680b1236cedea6399362a8814ab297b"

    [[ne_110m_populated_places.download]]
    sha256 = "a21bdbdfc6d38d56c68f17773ffcbb1f25fa4203af3d1af1ac283bfa334bb29d"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_110m_populated_places.tar.gz"

[ne_50m_admin_0_countries]
git-tree-sha1 = "f40389879f8d1525fd9efa1ba6d21e60ab085419"

    [[ne_50m_admin_0_countries.download]]
    sha256 = "b3471aa5834d38b4dab82932fd28f48abbf121cf0f318c99ff0c8ded07770194"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_50m_admin_0_countries.tar.gz"

[ne_50m_coastline]
git-tree-sha1 = "415eac65b4305428aa6d904c9e2dbf0932f36213"

    [[ne_50m_coastline.download]]
    sha256 = "df27973110de0319bf28addc9a9a99a8e4642be863ba8d3127398280251c1c9a"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_50m_coastline.tar.gz"

[ne_50m_land]
git-tree-sha1 = "ba7aefcecc2124ebefaf3bbe2b1fa669f8895eac"

    [[ne_50m_land.download]]
    sha256 = "01cebcb75f71c19f3cfd420a4d4274d371d731e58835ca00d6423ef94db61d1d"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_50m_land.tar.gz"

[ne_50m_populated_places]
git-tree-sha1 = "a353e69ad47b2d3b3ec20711be765f29e5679cc6"

    [[ne_50m_populated_places.download]]
    sha256 = "4c3204a06a0b4fe1a70167418b7dbedf1cc70ec990bd60327e33c58d7c7662ed"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/ne_50m_populated_places.tar.gz"

[skymap]
git-tree-sha1 = "069c69ca948deb29376f478c394cba5de540814e"
lazy = true

    [[skymap.download]]
    sha256 = "8d8a660e05d06f7fca67e1cc62629e81e7a7c59e76635b15b58ec8e214c0337e"
    url = "https://github.com/MakieOrg/GeoMakieArtifacts.jl/releases/download/v1.0.0/skymap.tar.gz"
