name = "GeoMakieArtifacts"
uuid = "c06dcbe2-c11f-4421-b8ce-2adf73295f27"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com> and contributors"]
version = "1.0.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"

[compat]
Artifacts = "1"
LazyArtifacts = "1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
